### ISSUE TITLE
v1.8.3 fails to run after recent client update

### ISSUE THREAD

**Issue by lainverse** [baslack/Killroy#9]
...a\Roaming\NCSOFT\WildStar\Addons\Killroy\Killroy.lua:423: attempt to index global 'tViewed' (a nil value)
stack trace:
    ...a\Roaming\NCSOFT\WildStar\Addons\Killroy\Killroy.lua:423: in function <...a\Roaming\NCSOFT\WildStar\Addons\Killroy\Killroy.lua:402>

...a\Roaming\NCSOFT\WildStar\Addons\Killroy\Killroy.lua:421: attempt to index global 'tData' (a nil value)
stack trace:
    ...a\Roaming\NCSOFT\WildStar\Addons\Killroy\Killroy.lua:421: in function <...a\Roaming\NCSOFT\WildStar\Addons\Killroy\Killroy.lua:402>

**Comment by baslack** [comment]
Currently unable to reproduce this. Logged in game at the moment and we're working fine. The errors you're point out have to do with loading tables from ChatLog, so if something interfered there, it would make sense that Killroy wouldn't be able to find those tables. My first advice is to always clear out your preferences for Killroy and ChatLog and see if you load up correctly. Try that first, and let me know what happens.

**Comment by lainverse** [comment]
Hi, removal of ChatLog and Killroy prefs helped and error disappeared. Thanks.
